_wandb:
    value:
        cli_version: 0.21.0
        e:
            6q6ro820dhp3n8lip3htq0qzetck21dg:
                codePath: finetune_llama.py
                codePathLocal: finetune_llama.py
                cpu_count: 10
                cpu_count_logical: 16
                cudaVersion: "12.4"
                disk:
                    /:
                        total: "502392610816"
                        used: "164444348416"
                email: vishnurosh24@gmail.com
                executable: /home/vishnu/code/projects/DocuMenotr AI/documentor_venv/bin/python3
                git:
                    commit: 09ecaba58c74555f086d1c96a087b81f72c766d5
                gpu: NVIDIA GeForce RTX 3070 Laptop GPU
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 5120
                      memoryTotal: "8589934592"
                      name: NVIDIA GeForce RTX 3070 Laptop GPU
                      uuid: GPU-20d55551-6a8d-fd51-bd04-e8e8a15e5e44
                host: PECE
                memory:
                    total: "16370491392"
                os: Linux-6.8.0-64-generic-x86_64-with-glibc2.39
                program: /home/vishnu/code/projects/DocuMenotr AI/./finetune_llama.py
                python: CPython 3.12.3
                root: /home/vishnu/code/projects/DocuMenotr AI
                startedAt: "2025-07-23T22:32:37.349168Z"
                writerId: 6q6ro820dhp3n8lip3htq0qzetck21dg
        m: []
        python_version: 3.12.3
        t:
            "1":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 51
                - 53
                - 71
                - 98
                - 105
            "2":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 51
                - 53
                - 71
                - 98
                - 105
            "3":
                - 13
            "4": 3.12.3
            "5": 0.21.0
            "6": 4.53.3
            "12": 0.21.0
            "13": linux-x86_64
